#!/usr/bin/env node

npm i commander chalk clipboardy

process.argv -- array of command line argument

const program = require('commander');
const chalk = require('chalk');
const clipboardy = require('clipboardy');

const createPassword = require('./utils/createPassword');
const savePassword = require('./utils/savePassword');
const log = console.log;

program.version('1.0.0').description('Simple Password Generator');
program
	// .command('generate')		// node index generate
	// .action(() => {			// do action in function
	// })
	.option('-l, --length <number>', 'length of password', '8')
	.option('-s, --save', 'save password to passwords.txt')     // boolean value
	.option('-nn, --no-numbers', 'remove numbers')
	.option('-ns, --no-symbols', 'remove symbols')
	.parse();

node index -h
node index -V

const { length, save, numbers, symbols } = program.opts()			// object. node index --length=10		{length: 10}

// Get generated password
const generatedPassword = createPassword(length, numbers, symbols);

// Save to file
if(save) {
	savePassword(generatedPassword);
}

// Output generated password
log(chalk.blue('Generated: ') + chalk.bold(generatedPassword));

// Copy to clipboard
clipboardy.writeSync(generatedPassword);
log(chalk.yellow('Password copied to clipboard');

----------------------------------------------------------------------------
createPassword.js
==================
const alpha = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
const numbers = '0123456789';
const symbols = '!@#$%^&*_-+=';

const createPassword = (length=8, hasNumbers=true, hasSymbols=true) => {
	let chars = alpha;
	hasNumbers ? (chars += numbers) : '';
	hasSymbols ? (chars += symbols) : '';

	return generatePassword(length, chars);
};

const generatePassword = (length, chars) => {
	let password = '';
	for(let i = 0; i < length; i++) {
		password += chars.charAt(Math.floor(Math.random() * chars.length));
	}
	return password;
};
module.exports = createPassword;
---------------------------------------------------------------------------
savePassword.js
================
const fs = require('fs');
const path = require('path');
const os = require('os');
const chalk = require('chalk');

const savePassword = password => {
	fs.open(path.join(__dirname, '../', 'passwords.txt', 'a', 666, (e, id) => {
		fs.write(id, password + os.EOL, null, 'utf-8', () => {
			fs.close(id, () => {
				console.log(chalk.green('Password saved to passwords.txt'));
			});
		});
	});
};
module.exports = savePassword;
=====================================================================================
=====================================================================================
package.json
=============
"main": "index.js",
"preferGlobal": true,
"bin": "./index.js",
...


npm link 		npm unlink
passgen
